language: python
python:
  - "3.6"
jobs:
 include:
   - stage: SDK Generation
     language: java
     jdk: openjdk8
     script:
      - git clone https://pallavigopi:$BITBUCKET_TOKEN@bitbucket.org/shoonyacloud/esper-sdk-config.git
  #  - stage: Update version and repository  
# # command to install dependencies
# install: "pip install -r requirements.txt"

# # command to run tests
# script: python test/scripts/test_env.py
