language: python
python:
  - "3.6"
jobs:
 include:
   - stage: Version Updation
     language: python
     script:
      - git clone --quiet https://pallavigopi:$BITBUCKET_TOKEN@bitbucket.org/shoonyacloud/esper-sdk-config.git
      - cd esper-sdk-config
      - export SDK_VERSION=$(git -c 'versionsort.suffix=-' ls-remote --tags --sort='v:refname' https://github.com/pallavigopi/esper-api-spec | cut --delimiter='/' --fields=3)
      - python3 update_version.py
      - git config --global user.email "travis@travis-ci.org"
      - git config --global user.name "Travis CI"
      - git add . && git commit -m "$TRAVIS_BUILD_NUMBER Update SDK Version number"
      - git push -u origin sdk-build-automation
   - stage: SDK Generation
     language: java
     jdk: openjdk8
     script:
      - git clone --quiet https://pallavigopi:$BITBUCKET_TOKEN@bitbucket.org/shoonyacloud/esper-sdk-config.git
      - cd esper-sdk-config
      - wget -q https://repo1.maven.org/maven2/io/swagger/swagger-codegen-cli/2.4.4/swagger-codegen-cli-2.4.4.jar
      - git clone -quiet https://$GITHUB_TOKEN@github.com/pallavigopi/esper-client-py.git -b sdk-build-automation
      - java -jar swagger-codegen-cli-2.4.4.jar generate -i ./esper-api-spec.yaml -l python -c ./sdk-config/python-config.json --template-dir ./sdk-templates/python/ -o esper-client-py -s
      - cd esper-client-py
      - git config --global user.email "travis@travis-ci.org"
      - git config --global user.name "Travis CI"
      - git add .
      - git status
      - git commit -m "Travis Build $TRAVIS_BUILD_NUMBER"
      - git push -u origin sdk-build-automation

      #random commit ok
      #  - stage: Update version and repository  
# # command to install dependencies
# install: "pip install -r requirements.txt"

# env:
#   - PYTHONPATH=.

# # command to install dependencies
# install: "pip install -r requirements.txt"

# # command to run tests
# script: python test/scripts/test_env.py
