#test the sdk
#build dist
#push to pypi

language: python
python:
  - "3.6"
jobs:
 include:
   - stage: Perform tests
     env:
      - PYTHONPATH=.
     if: tag IS present
     install: "pip install -r requirements.txt"
     script: python test/scripts/test_env.py
   - stage: Push SDK to pypi
     if: tag IS present
     script:
      #script here
      - ls
      - pwd
