language: python
python:
  - "3.6"
jobs:
 include:
   - stage: SDK Generation
     language: java
     jdk: openjdk8
     script: esper-client-py/generateSDK.sh
  #  - stage: Update version and repository  
# # command to install dependencies
# install: "pip install -r requirements.txt"

# # command to run tests
# script: python test/scripts/test_env.py
